In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("../data/raw/E-commerece sales data 2024(dataset5).csv",index_col=False)

In [4]:
data.head()

,user id,product id,Interaction type,Time stamp,Unnamed: 4
0,1.0,4c69b61db1fc16e7013b43fc926e502d,purchase,10/10/2023 8:00,NaN
1,2.0,66d49bbed043f5be260fa9f7fbff5957,view,11/10/2023 8:00,NaN
2,3.0,2c55cae269aebf53838484b0d7dd931a,like,12/10/2023 8:00,NaN
3,4.0,18018b6bc416dab347b1b7db79994afa,view,13/10/2023 8:00,NaN
4,5.0,e04b990e95bf73bbe6a3fa09785d7cd0,like,14/10/2023 8:00,NaN

In [9]:
data.dtypes

user id             float64
product id           object
Interaction type     object
Time stamp           object
Unnamed: 4          float64
dtype: object

In [10]:
data.describe()

           user id  Unnamed: 4
count  2999.000000         0.0
mean   1500.000000         NaN
std     865.881054         NaN
min       1.000000         NaN
25%     750.500000         NaN
50%    1500.000000         NaN
75%    2249.500000         NaN
max    2999.000000         NaN

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3294 entries, 0 to 3293
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user id           2999 non-null   float64
 1   product id        2999 non-null   object
 2   Interaction type  2871 non-null   object
 3   Time stamp        2999 non-null   object
 4   Unnamed: 4        0 non-null      float64
dtypes: float64(2), object(3)
memory usage: 128.8+ KB

In [12]:
data.nunique()

user id             2999
product id          2999
Interaction type       3
Time stamp           366
Unnamed: 4             0
dtype: int64

In [26]:
#drop useless column
data = data.drop(columns=['unnamed:_4'])

In [27]:
#check for missing values
data.isnull().sum()

user_id             0
product_id          0
interaction_type    0
time_stamp          0
dtype: int64

In [14]:
#handles missing values
data = data.fillna(method='ffill')

C:\Users\majum\AppData\Local\Temp\ipykernel_3316\410179031.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = data.fillna(method='ffill')

In [19]:
#check and remove for duplicates
data.duplicated().sum()
data=data.drop_duplicates()

In [22]:
#clean column names
data.columns = (data.columns.str.strip().str.lower().str.replace(" ", "_"))

In [30]:
#fix data types
data['user_id'] = data['user_id'].astype(int)
data['time_stamp'] = pd.to_datetime(data['time_stamp'], dayfirst=True)

In [34]:
#feature engineering 
data['year'] = data['time_stamp'].dt.year
data['month'] = data['time_stamp'].dt.month
data['day'] = data['time_stamp'].dt.day

In [37]:
#standardize interaction type
data['interaction_type'] = data['interaction_type'].str.lower()

In [39]:
data.dtypes

user_id                      int64
product_id                  object
interaction_type            object
time_stamp          datetime64[ns]
year                         int32
month                        int32
day                          int32
dtype: object

In [41]:
data.to_csv("../data/processed/dataset5_clean.csv",index=False)